name: Deploy Angular App

on:
  push:
    branches:
      - main

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Angular
        run: npm run build -- --configuration production --base-href /Bingo/

      - name: Create 404 fallback
        run: cp dist/demoweb/browser/index.html dist/demoweb/browser/404.html

      - name: Upload Angular build
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist/demoweb/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
